export default [
  {
    id: 1,
    img: "http://d3ugyf2ht6aenh.cloudfront.net/stores/536/222/products/1_1000x1000-11-f95ee48af0a0ff1b5716201480108757-640-0.jpg",
    nombre: "Máquina 1",
    marca: "Marca 1",
    precio: 100,
    stock: 10,
    categoria: "Categoria 1",
  },
  {
    id: 2,
    img: "https://www.superprof.mx/blog/wp-content/uploads/2018/01/maquina-coser.jpg",
    nombre: "Máquina 2",
    marca: "Marca 2",
    precio: 200,
    stock: 20,
    categoria: "Categoria 2",
  },
  {
    id: 3,
    img: "https://www.superprof.mx/blog/wp-content/uploads/2018/01/maquina-coser.jpg",
    nombre: "Máquina 3",
    marca: "Marca 3",
    precio: 300,
    stock: 30,
    categoria: "Categoria 3",
  },
  {
    id: 4,
    img: "https://www.superprof.mx/blog/wp-content/uploads/2018/01/maquina-coser.jpg",
    nombre: "Máquina 3",
    marca: "Marca 3",
    precio: 300,
    stock: 30,
    categoria: "Categoria 3",
  },
  {
    id: 5,
    img: "https://www.superprof.mx/blog/wp-content/uploads/2018/01/maquina-coser.jpg",
    nombre: "Máquina 3",
    marca: "Marca 3",
    precio: 300,
    stock: 30,
    categoria: "Categoria 3",
  },
  {
    id: 6,
    img: "https://www.superprof.mx/blog/wp-content/uploads/2018/01/maquina-coser.jpg",
    nombre: "Máquina 3",
    marca: "Marca 3",
    precio: 300,
    stock: 30,
    categoria: "Categoria 3",
  },
  {
    id: 6,
    img: "https://www.superprof.mx/blog/wp-content/uploads/2018/01/maquina-coser.jpg",
    nombre: "Máquina 3",
    marca: "Marca 3",
    precio: 300,
    stock: 30,
    categoria: "Categoria 3",
  },
  {
    id: 6,
    img: "https://www.superprof.mx/blog/wp-content/uploads/2018/01/maquina-coser.jpg",
    nombre: "Máquina 3",
    marca: "Marca 3",
    precio: 300,
    stock: 30,
    categoria: "Categoria 3",
  },
  {
    id: 6,
    img: "https://www.superprof.mx/blog/wp-content/uploads/2018/01/maquina-coser.jpg",
    nombre: "Máquina 3",
    marca: "Marca 3",
    precio: 300,
    stock: 30,
    categoria: "Categoria 3",
  },
  {
    id: 6,
    img: "https://www.superprof.mx/blog/wp-content/uploads/2018/01/maquina-coser.jpg",
    nombre: "Máquina 3",
    marca: "Marca 3",
    precio: 300,
    stock: 30,
    categoria: "Categoria 3",
  },
];
